name: "Container multi-Image Build pi4-ntopng"

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        default: false
        required: true
        description: "Push the image after the build?"

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install qemu dependency
        run: |-
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Get ntopng Version
        run: |-
          VERSION="3.8.190813"    # Ubuntu focal version
          echo "APP_VERSION=${VERSION}"
          echo "APP_VERSION=${VERSION}" >> $GITHUB_ENV

      - id: container
        name: Build Container Image
        uses: redhat-actions/buildah-build@b4dc19b4ba891854660ab1f88a097d45aa158f76 # v2.12
        with:
          image: pi4-ntopng
          tags: >-
            latest
            ${{ env.APP_VERSION }}
          oci: true
          platforms: linux/amd64, linux/arm64
          containerfiles: |-
            Dockerfile

      - name: Push container image to ghcr.io
        if: ${{ (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.publish)) && github.ref == 'refs/heads/main' }}
        uses: redhat-actions/push-to-registry@9986a6552bc4571882a4a67e016b17361412b4df # v2.7
        with:
          image: ${{ steps.container.outputs.image }}
          tags: ${{ steps.container.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

